#!/bin/bash
#!/usr/bin/env bash
usage() {
    pname=$(basename $0)
    echo "$pname --operat <operat type> --run_user <run user> --domain_path <domain path> --http_url <admin http url> --server_name <manager server name> --server_port <server port>" 
    exit -1
}

parseOpts() {
    OPT_SPEC=":h-:"
    while getopts "$OPT_SPEC" optchar; do
        case "${optchar}" in
        -)
            case "${OPTARG}" in
            operat)
                operat="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            run_user)
                run_user="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            domain_path)
                domain_path="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            http_url)
                http_url="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            server_name)
                server_name="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            server_port)
                server_port="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            timeout)
                timeout="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            *)
                if [ "$OPTERR" = 1 ] && [ "${OPT_SPEC:0:1}" != ":" ]; then
                    echo "Unknown option --${OPTARG}" >&2
                fi
                ;;
            esac
            ;;
        h)
            usage
            exit 2
            ;;
        *)
            if [ "$OPTERR" != 1 ] || [ "${OPT_SPEC:0:1}" = ":" ]; then
                echo "Non-option argument: '-${OPTARG}'" >&2
            fi
            ;;
        esac
    done
}

parseOpts "$@"

if [[  ! -n "$domain_path" ]] ; then
    echo "ERROR:: Must defined domain_path."
    usage
fi 

if [[  ! -n "$run_user" ]] ; then
    echo "ERROR:: Must defined run_user."
    usage
fi 

if [[  ! -n "$http_url"  && "$operat" == "start" ]] ; then
    echo "ERROR:: Must defined http_url."
    usage
fi 

if [[  ! -n "$server_name" && "$operat" == "start" ]] ; then
    echo "ERROR:: Must defined server_name."
    usage
fi 

if [[  ! -n "$server_port" && "$operat" == "start" ]] ; then
    echo "ERROR:: Must defined server_port."
    usage
fi 

if [[  ! -n "$operat" ]] ; then
    operat="start"
fi 

if [[ ! -n "$timeout" ]] ; then 
    timeout=60
fi 

temp_file="/tmp/weblogic.log"
port=`netstat -anp|grep $server_port`
pinfo=`ps -ef | grep weblogic | grep "$server_name" | grep -v grep | awk '{print $2}'`
if [[ "$operat" == "start" ]] ; then 
    if [[ -n "$port" && -n "$pinfo" ]]; then
        echo "FINE:: Weblogic ManagerServer $server_name already start."
        exit 0
    else 
        su - "$run_user" -c "nohup $domain_path/bin/startManagedWebLogic.sh \"$server_name\" \"$http_url\" > $temp_file  2>&1 &"
    fi 
else
    if [[ ! -n "$port" && ! -n "$pinfo"  ]]; then
        echo "FINE:: Weblogic ManagerServer $server_name already stop."
        exit 0
    else 
        su - "$run_user" -c "nohup $domain_path/bin/stopManagedWebLogic.sh \"$server_name\" > $temp_file 2>&1 &"
    fi 
fi

if [ $? != 0  ] ;then 
    echo "Weblogic ManagerServer $server_name $operat failed.$@"
    exit 1
fi 

loopcount=$((timeout/5))
exitCode=1
if [[ "$operat" == "start" ]] ; then 
    while [ $exitCode != 0 ]
    do
        loopcount=$((loopcount-1))
        port=`netstat -anp|grep $server_port`
        if [ -n "$port" ]; then
            exitCode=0
            tail -n 200 $temp_file
            echo "FINE:: Start Weblogic ManagerServer $server_name success."
            rm -f $temp_file
        else
            echo "INFO:: Start Weblogic ManagerServer $server_name Running..."
        fi
        sleep 5

        if [[ $loopcount == 0 ]] ; then 
            tail -n 200 $temp_file
            echo "ERROR:: Start Weblogic ManagerServer $server_name failed."
            exitCode=2
            break
        fi
    done
    exit $exitCode
else 
    while [ $exitCode != 0 ]
    do
        loopcount=$((loopcount-1))
        pid=`ps -ef | grep weblogic |grep $server_name |awk '{print $2}'`
        if [ ! -n "$pid" ]; then
            exitCode=0
            tail -n 200 $temp_file
            echo "FINE:: Stop Weblogic ManagerServer $server_name success."
            rm -f $temp_file
        else
            echo "INFO:: Stop Weblogic ManagerServer $server_name Running..."
        fi
        sleep 5

        if [[ $loopcount == 0 ]] ; then 
            kill -9 $pid
            tail -n 200 $temp_file
            echo "FINE:: Stop Weblogic ManagerServer $server_name success."
            rm -f $temp_file
            exitCode=0
            break
        fi
    done
    exit $exitCode
fi
