#!/bin/bash
#!/usr/bin/env bash
usage() {
    pname=$(basename $0)
    echo "$pname --weblogic_path <install path> --domain_path <domain path> --run_user <run user> --listen_port <adminserver listen port>"
    exit -1
}

parseOpts() {
    OPT_SPEC=":h-:"
    while getopts "$OPT_SPEC" optchar; do
        case "${optchar}" in
        -)
            case "${OPTARG}" in
            run_user)
                run_user="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            weblogic_path)
                weblogic_path="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            domain_path)
                domain_path="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            listen_port)
                listen_port="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            *)
                if [ "$OPTERR" = 1 ] && [ "${OPT_SPEC:0:1}" != ":" ]; then
                    echo "Unknown option --${OPTARG}" >&2
                fi
                ;;
            esac
            ;;
        h)
            usage
            exit 2
            ;;
        *)
            if [ "$OPTERR" != 1 ] || [ "${OPT_SPEC:0:1}" = ":" ]; then
                echo "Non-option argument: '-${OPTARG}'" >&2
            fi
            ;;
        esac
    done
}

parseOpts "$@"

if [[  ! -n "$weblogic_path" ]] ; then
    echo "ERROR:: Must defined weblogic_path."
    usage
fi 

if [[  ! -n "$domain_path" ]] ; then
    echo "ERROR:: Must defined domain_path."
    usage
fi 

cd $domain_path/user_projects/domains/base_domain/bin/
#后台启动WebLogic
sudo -u $run_user nohup ./startWebLogic.sh > $weblogic_path/weblogic_run.log 2>&1 &
if [ $? != 0 ]
then
    echo "ERROR:: start WebLogic failed."
else
    echo "INFO:: start WebLogic success."
fi

#判断adminserver是否启动
n=1
while [ $n != 0 ]
do
    port=`netstat -anp|grep $listen_port`
    if [ -n "$port" ]; then
        n=0
        echo "INFO:: adminserver launch succeed."
    else
        echo "ERROR:: adminserver didn't launch yet."
    fi
    sleep 5
done
