#!/usr/bin/perl
#配置mysql my.cnf文件

use FindBin;
use lib "$FindBin::Bin/lib";
use lib "$FindBin::Bin/lib/perl-lib/lib/perl5";

use IO::File;
use strict;
use Config::Tiny;
use Getopt::Long;
use JSON qw(to_json from_json encode_json);


sub usage {
    my $pname = $FindBin::Script;

    print("$pname --ip2server <ip and server id relation> \n");
    exit(1);
}

sub main {
    my ( $isHelp, $ip2server );
    GetOptions(
        'h|help'     => \$isHelp,
        'ip2server=s' => \$ip2server
    );

    if ($isHelp) {
        usage();
    }
    my $hasOptErr = 0;
    if ( not defined($ip2server) or $ip2server eq '' ) {
        $hasOptErr = 1;
        print("ERROR: Must defined ip and server id relation by option --ip2server.\n");
    }
    if ( $hasOptErr == 1 ) {
        usage();
    }

    my $ip2serverJson = from_json($ip2server);
    my $nodehost = $ENV{NODE_HOST};
    my $serverid = $ip2serverJson->{$nodehost};

    my $exitCode = system("service mysql stop");

    my $Config = Config::Tiny->new;
    $Config = Config::Tiny->read( '/etc/my.cnf', 'utf8' );

    $Config->{mysqld}->{'server_id'} = "$serverid";
    $Config->{mysqld}->{'log-slave-updates'} = '1';
    $Config->{mysqld}->{'relay_log'} = 'relay-bin-log';

    $Config->write( '/etc/my.cnf', 'utf8' );

    $exitCode = system("service mysql start");

    return $exitCode;
}

exit main();
