#!/bin/bash

usage(){
    pname=$(basename $0)
    echo "Usage:"
    echo "$pname --rootpwd <root login use password> --masterip <mysql master ip>"
    exit -1
}

parseOpts() {
    OPT_SPEC=":h-:"
    while getopts "$OPT_SPEC" optchar; do
        case "${optchar}" in
        -)
            case "${OPTARG}" in
            rootpwd)
                rootpwd="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            masterip)
                masterIp="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
            ;;
            *)
                if [ "$OPTERR" = 1 ] && [ "${OPT_SPEC:0:1}" != ":" ]; then
                    echo "Unknown option -- ${OPTARG}" >&2
                fi
                ;;
            esac
            ;;
        h)
            usage
            exit 2
            ;;
        *)
            if ["$OPTERR" != 1 ] || [ "${OPT_SPEC:0:1}" = ":" ]; then
                echo "Non-option argument: '-${OPTARG}'" >&2
            fi
            ;;
        esac
    done
}
parseOpts "$@"

function DO_CMD() {
    echo Exec ommand: $@
    $@

    if [ $? != 0 ]; then
        HAS_ERROR=$?
        echo ERROR: Execute failed.
        exit $HAS_ERROR
    else
        echo FINE: Execute success.
    fi
}

DO_CMD service mysql stop

DO_CMD sed -bi 's/^\s*server_id\s*=.*$/server_id=2/g' /etc/my.cnf
DO_CMD sed -bi 's/^\s*#\s*log-slave-updates\s*=.*$/log-slave-updates=1/g' /etc/my.cnf
DO_CMD echo  "relay_log=relay-bin-log" >> /etc/my.cnf

DO_CMD service mysql start

mysql -v --connect-expired-password  -uroot -p$rootpwd << EOF
        stop slave;
        CHANGE MASTER TO MASTER_HOST='$masterIp',MASTER_USER='root',MASTER_PASSWORD='$rootpwd',MASTER_LOG_FILE='$binLogFile',MASTER_LOG_POS=$binLogOffset;
        start slave;
        show slave status\\G;
EOF

if [ $? != 0 ]
then
	echo "ERROR: set slave bin-log start postion failed."
	exit 1;
fi

errorState=`
mysql -uroot -p$rootpwd 2>/dev/null << EOF | grep -i Last_IO_Errno: | awk '{print $2}'
	show slave status\\G;
EOF
`

if [ ! -z "$errorState" ]
then
	echo "ERROR: error slave state."
	exit 1;
fi
