#!/bin/bash

usage(){
    pname=$(basename $0)
    echo "Usage:"
    echo "$pname --rootpwd <root login use password> "
    exit -1
}

parseOpts() {
    OPT_SPEC=":h-:"
    while getopts "$OPT_SPEC" optchar; do
        case "${optchar}" in
        -)
            case "${OPTARG}" in
            rootpwd)
                rootpwd="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            *)
                if [ "$OPTERR" = 1 ] && [ "${OPT_SPEC:0:1}" != ":" ]; then
                    echo "Unknown option -- ${OPTARG}" >&2
                fi
                ;;
            esac
            ;;
        h)
            usage
            exit 2
            ;;
        *)
            if ["$OPTERR" != 1 ] || [ "${OPT_SPEC:0:1}" = ":" ]; then
                echo "Non-option argument: '-${OPTARG}'" >&2
            fi
            ;;
        esac
    done
}
parseOpts "$@"

masterStatus=`
mysql -uroot --connect-expired-password -p$rootpwd << EOF
        use mysql;
        show master status;
EOF
`
echo $masterStatus

binLogOffset=`echo $masterStatus | awk '{print $NF}'`
binLogFile=`echo $masterStatus | awk '{print $(NF-1)}'`
echo "bin log file:$binLogFile"
echo "bin log offset:$binLogOffset"

if [ -z  "$binLogOffset" ]
then
	echo "ERROR: get bin log position failed."
	exit 1;
fi

#Save bin-log
cat <<EOF >"output.json"
{
    "binLogOffset":"$binLogOffset",
    "binLogFile":"$binLogFile"
}
EOF