#!/usr/bin/perl
#停止mysql服务

use FindBin;
use lib "$FindBin::Bin/lib";
use lib "$FindBin::Bin/lib/perl-lib/lib/perl5";

use strict;


sub main {

    my $exitCode = system("service mysql stop");

    return $exitCode;
}

exit main();