#!/bin/bash
#ORACLE_USER=${ORACLE_USER}
#UNIX_GROUP_NAME=${UNIX_GROUP_NAME}
#INVENTORY_LOCATION=${INVENTORY_LOCATION}
#ORACLE_BASE=${ORACLE_BASE}
#ORACLE_HOME=${ORACLE_HOME}
#GRID_BASE=${GRID_BASE}
#GRID_HOME=${GRID_HOME}
#OSDBA_GROUP=${OSDBA_GROUP}
#OSOPER_GROUP=${OSOPER_GROUP}
#OSBACKUPDBA_GROUP=${OSBACKUPDBA_GROUP}
#OSDGDBA_GROUP=${OSDGDBA_GROUP}
#OSKMDBA_GROUP=${OSKMDBA_GROUP}
#OSRACDBA_GROUP=${OSRACDBA_GROUP}

#CLUSTER_NODES=oracle19crac01,oracle19crac02

function createOraDir() {
    if [ ! -e "$INVENTORY_LOCATION" ]; then
        mkdir -p $INVENTORY_LOCATION
        chown -R $ORACLE_USER:$INSTALL_GROUP $INVENTORY_LOCATION
        chmod -R 775 $INVENTORY_LOCATION
    fi

    mkdir -p $ORACLE_BASE
    mkdir -p $ORACLE_BASE/cfgtoollogs
    mkdir -p $ORACLE_HOME
    chown -R $ORACLE_USER:$INSTALL_GROUP $ORACLE_BASE
    chmod -R 775 $ORACLE_BASE
}

function prepareRspFile() {
    if [ ! -e "$RESPONSE_FILE" ]; then
        echo "ERROR: Response file $RESPONSE_FILE not exist."
        exit 3
    fi

    sed -i s/'^\s*UNIX_GROUP_NAME\s*=.*$'/"UNIX_GROUP_NAME=$UNIX_GROUP_NAME"/ $RESPONSE_FILE
    sed -i s/'^\s*oracle.install.db.OSDBA_GROUP\s*=.*$'/"oracle.install.db.OSDBA_GROUP=$OSDBA_GROUP"/ $RESPONSE_FILE
    sed -i s/'^\s*oracle.install.db.OSOPER_GROUP\s*=.*$'/"oracle.install.db.OSOPER_GROUP=$OSOPER_GROUP"/ $RESPONSE_FILE
    sed -i s/'^\s*oracle.install.db.OSBACKUPDBA_GROUP\s*=.*$'/"oracle.install.db.OSBACKUPDBA_GROUP=$OSBACKUPDBA_GROUP"/ $RESPONSE_FILE
    sed -i s/'^\s*oracle.install.db.OSDGDBA_GROUP\s*=.*$'/"oracle.install.db.OSDGDBA_GROUP=$OSDGDBA_GROUP"/ $RESPONSE_FILE
    sed -i s/'^\s*oracle.install.db.OSKMDBA_GROUP\s*=.*$'/"oracle.install.db.OSKMDBA_GROUP=$OSKMDBA_GROUP"/ $RESPONSE_FILE
    sed -i s/'^\s*oracle.install.db.OSRACDBA_GROUP\s*=.*$'/"oracle.install.db.OSRACDBA_GROUP=$OSRACDBA_GROUP"/ $RESPONSE_FILE
    
    sed -i s/'^\s*ORACLE_BASE\s*=.*$'/"ORACLE_BASE=$ORACLE_BASE"/ $RESPONSE_FILE
    sed -i s/'^\s*ORACLE_HOME\s*=.*$'/"ORACLE_HOME=$ORACLE_HOME"/ $RESPONSE_FILE
    sed -i s/'^\s*INVENTORY_LOCATION\s*=.*$'/"INVENTORY_LOCATION=$INVENTORY_LOCATION"/ $RESPONSE_FILE
    sed -i s/'^\s*oracle.install.db.CLUSTER_NODES\s*=.*$'/"oracle.install.db.CLUSTER_NODES=$CLUSTER_NODES"/ $RESPONSE_FILE

    echo "USE $RESPONSE_FILE to setup silent...."
    cat $RESPONSE_FILE
}

#参数处理,全部用长参数
######################################
function parseOpts() {
    OPT_SPEC=":h-:"
    while getopts "$OPT_SPEC" optchar; do
        case "${optchar}" in
        -)
            case "${OPTARG}" in
            RSPONSE_FILE)
                RSPONSE_FILE="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            EXEC_ENV)
                EXEC_ENV="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            CLUSTER_NODES)
                CLUSTER_NODES="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            *)
                if [ "$OPTERR" = 1 ] && [ "${OPT_SPEC:0:1}" != ":" ]; then
                    echo "Unknown option --${OPTARG}" >&2
                fi
                ;;
            esac
            ;;
        h)
            usage
            exit 2
            ;;
        *)
            if [ "$OPTERR" != 1 ] || [ "${OPT_SPEC:0:1}" = ":" ]; then
                echo "Non-option argument: '-${OPTARG}'" >&2
            fi
            ;;
        esac
    done
}

parseOpts "$@"

#unzip安装包到$ORACLE_HOME下，chown oracle:oinstall

#静默安装DB软件
#su - oracle
$ORACLE_HOME/runInstaller -silent -force -noconfig -ignorePrereq \
    oracle.install.option=INSTALL_DB_SWONLY \
    UNIX_GROUP_NAME=oinstall \
    INVENTORY_LOCATION=/u01/app/oraInventory \
    ORACLE_BASE=/u01/app/oracle \
    ORACLE_HOME=/u01/app/oracle/product/19.0.0/dbhome_1 \
    oracle.install.db.InstallEdition=EE \
    oracle.install.db.OSDBA_GROUP=dba \
    oracle.install.db.OSOPER_GROUP=oper \
    oracle.install.db.OSBACKUPDBA_GROUP=backupdba \
    oracle.install.db.OSDGDBA_GROUP=dgdba \
    oracle.install.db.OSKMDBA_GROUP=kmdba \
    oracle.install.db.OSRACDBA_GROUP=racdba \
    oracle.install.db.CLUSTER_NODES=oracle19crac01,oracle19crac02 \
    oracle.install.db.isRACOneInstall=false \
    oracle.install.db.rac.serverpoolCardinality=0 \
    oracle.install.db.config.starterdb.type=GENERAL_PURPOSE \
    oracle.install.db.ConfigureAsContainerDB=false \
    SECURITY_UPDATES_VIA_MYORACLESUPPORT=false \
    DECLINE_SECURITY_UPDATES=true

#执行$ORACLE_HOME/root.sh

#创建数据库
#su - oracle
dbca -silent -createDatabase \
    -templateName General_Purpose.dbc \
    -gdbname racdb -sid racdb \
    -responseFile NO_VALUE \
    -characterSet AL32UTF8 \
    -sysPassword oracle -systemPassword oracle -pdbAdminPassword oracle -dbsnmpPassword oracle \
    -datafileDestination '+datadg' \
    -createAsContainerDatabase false \
    -databaseType MULTIPURPOSE \
    -automaticMemoryManagement false \
    -totalMemory 2385 \
    -redoLogFileSize 50 \
    -emConfiguration NONE \
    -ignorePreReqs \
    -nodelist oracle19crac01,oracle19crac02 \
    -storageType ASM \
    -diskGroupName +datadg \
    -asmsnmpPassword oracle \
    -recoveryAreaDestination NONE

#集群验证
crsctl stat res -t
