#!/bin/bash
HAS_ERROR=0
function DO_CMD() {
    echo Exec ommand: $@
    $@
    EXIT_CODE=$?
    if [ $EXIT_CODE != 0 ]; then
        HAS_ERROR=1
        echo ERROR: Execute $@ failed.
        exit $EXIT_CODE
    else
        echo FINE: Execute success.
    fi
}

function SUDO_CMD() {
    USER=$1
    shift
    echo "Exec ommand: su -u '$USER' -c '$@'"
    eval "sudo - '$USER' -c '$@'"
    EXIT_CODE=$?
    if [ $EXIT_CODE != 0 ]; then
        HAS_ERROR=1
        echo ERROR: Execute $@ failed.
        exit $EXIT_CODE
    else
        echo FINE: Execute success.
    fi
}

ORACLE_HOME=$1

if [ -n "$ORACLE_HOME" ]; then
    echo "ERROR: Argument not provided."
    echo "Usage: dbins-root <Oracle Home dir>"
    exit 2
fi

DO_CMD $ORACLE_HOME/root.sh

exit $HAS_ERROR
