#!/bin/bash
HAS_ERROR=0
function DO_CMD() {
    echo Exec ommand: $@
    $@
    EXIT_CODE=$?
    if [ $EXIT_CODE != 0 ]; then
        HAS_ERROR=1
        echo ERROR: Execute $@ failed.
        exit $EXIT_CODE
    else
        echo FINE: Execute success.
    fi
}

function SUDO_CMD() {
    USER=$1
    shift
    echo "Exec ommand: su - '$USER' -c '$@'"
    eval "su - '$USER' -c '$@'"
    EXIT_CODE=$?
    if [ $EXIT_CODE != 0 ]; then
        HAS_ERROR=1
        echo ERROR: Execute $@ failed.
        exit $EXIT_CODE
    else
        echo FINE: Execute success.
    fi
}

#参数处理,全部用长参数
######################################
function parseOpts() {
    OPT_SPEC=":h-:"
    while getopts "$OPT_SPEC" optchar; do
        case "${optchar}" in
        -)
            case "${OPTARG}" in
            ORACLE_HOME)
                ORACLE_HOME="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            *)
                if [ "$OPTERR" = 1 ] && [ "${OPT_SPEC:0:1}" != ":" ]; then
                    echo "Unknown option --${OPTARG}" >&2
                fi
                ;;
            esac
            ;;
        h)
            usage
            exit 2
            ;;
        *)
            if [ "$OPTERR" != 1 ] || [ "${OPT_SPEC:0:1}" = ":" ]; then
                echo "Non-option argument: '-${OPTARG}'" >&2
            fi
            ;;
        esac
    done
}

parseOpts "$@"

if [ -z "$ORACLE_HOME" ]; then
    echo "ERROR: ORACLE_HOME not defined."
    echo "Usage: dbins-root --ORACLE_HOME <oracle home>"
    exit 2
fi

$ORACLE_HOME/root.sh
exitCode=$?
if [ $exitCode -ge 128 ]; then
    #负数返回码，大于127就是负数的补码
    echo "ERROR: Execute $ORACLE_HOME/root.sh failed, exitCode:$exitCode."
    exit $exitCode
elif [ $exitCode -gt 0 ]; then
    echo "WARN: Execute $ORACLE_HOME/root.sh has some warning, exitCode:$exitCode."
else
    echo "FINE: Execute $ORACLE_HOME/root.sh successful."
fi
