#!/bin/bash
HAS_ERROR=0
function DO_CMD() {
    echo Exec ommand: $@
    $@
    EXIT_CODE=$?
    if [ $EXIT_CODE != 0 ]; then
        HAS_ERROR=1
        echo ERROR: Execute $@ failed.
        exit $EXIT_CODE
    else
        echo FINE: Execute success.
    fi
}

function SUDO_CMD() {
    USER=$1
    shift
    echo "Exec ommand: su - '$USER' -c '$@'"
    eval "sudo - '$USER' -c '$@'"
    EXIT_CODE=$?
    if [ $EXIT_CODE != 0 ]; then
        HAS_ERROR=1
        echo ERROR: Execute $@ failed.
        exit $EXIT_CODE
    else
        echo FINE: Execute success.
    fi
}

GRID_HOME=$1
if [ -z "$ORACLE_HOME" ]; then
    echo "ERROR: Argument not provided."
    echo "Usage: dbins-root <Oracle Home dir>"
    exit 2
fi

INVENTORY_DIR=$(cat $GRID_HOME/oraInst.loc | grep inventory_loc | sed s'/inventory_loc\s*=\s*//' | sed s'/\s*$//')

if [ -z "$INVENTORY_DIR" ]; then
    echo "ERROR: Can not determin invertory directory by file:$GRID_HOME/oraInst.loc."
    exit 3
fi

DO_CMD $INVENTORY_LOCATION/orainstRoot.sh
DO_CMD $GRID_HOME/root.sh

exit $HAS_ERROR
