#!/usr/bin/perl
my $str = q{
LISTENER =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = TCP)(HOST = ${NODE2_FQ_HOSTNAME})(PORT = 1521))
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
    )
  )

SID_LIST_LISTENER =
  (SID_LIST =
    (SID_DESC =
      (GLOBAL_DBNAME = ${NODE2_DB_UNIQUE_NAME})
      (SID_NAME = ${ORACLE_SID})
      (ORACLE_HOME = ${ORACLE_HOME})
    )
    (SID_DESC =
      (GLOBAL_DBNAME = ${NODE2_DB_UNIQUE_NAME}${DB_DOMAIN_STR})
      (SID_NAME = ${ORACLE_SID})
      (ORACLE_HOME = ${ORACLE_HOME})
    )
    (SID_DESC =
      (SID_NAME = ${ORACLE_SID})
      (GLOBAL_DBNAME = ${NODE2_DB_UNIQUE_NAME}_DGMGRL${DB_DOMAIN_STR})
      (ORACLE_HOME = ${ORACLE_HOME})
      (ENVS="TNS_ADMIN=${ORACLE_HOME}/network/admin")
    )
  )
};

#my @matches = $str =~ /(\w\s*=\s*\((?:\(.*\)|[^\)])*\)|\w+)/sg;

#使用嵌套正则表达式进行多层嵌套括号的匹配
my $descRe; 
$descRe = qr/\((?:(?>[^()]+)|(??{$descRe}))*\)/x; 

while ($str =~ /([^\s\(\)]+)\s*=\s*($descRe)/sg){
    my $name = $1;
    my $desc = $2;

    print ("============================\n");
    print("$name = \n$desc\n");
    print("------------------------------\n");
}
