#!/bin/bash
function DO_CMD() {
    echo Exec ommand: $@
    $@

    if [ $? != 0 ]; then
        HAS_ERROR=$?
        echo ERROR: Execute failed.
        exit $HAS_ERROR
    else
        echo FIND: Execute success.
    fi
}

DO_CMD $ORACLE_HOME/root.sh
