#!/bin/bash

disableNetworkManager() {
    if [ "$INIT_TYPE" = 'systemd' ];then
        systemctl stop NetworkManager
        systemctl disable NetworkManager
    else
        service NetworkManager stop
        chkconfig NetworkManager off
    fi
}

disableIptables() {
    if [ "$INIT_TYPE" = 'systemd' ];then
        systemctl stop firewalld
        systemctl disable firewalld
    else
        service iptables stop
        chkconfig iptables off
    fi
}

disableAvahi(){
    if [[ -f "/etc/systemd/system/dbus-org.freedesktop.Avahi.service" ]]; then
        systemctl stop avahi-dnsconfd
        systemctl stop avahi-daemon
        systemctl disable avahi-dnsconfd
        systemctl disable avahi-daemon
    fi
}

dependRpmInstall() {
    yum install -y openssh \
    pam \
    libXaw \
    unixODBC \
    nscd \
    binutils \
    compat-libcap1 \
    compat-libstdc++-33 \
    gcc \
    gcc-c++ \
    glibc \
    glibc-devel \
    ksh \
    libgcc \
    libstdc++ \
    libaio \
    libaio-devel \
    libXext \
    libXtst \
    libX11 \
    libXau \
    libxcb \
    libXi \
    make \
    sysstat \
    nfs-utils
}

tuningShmConf(){
    memTotal=$(grep MemTotal /proc/meminfo | awk '{print $2}')
    totalMemory=$((memTotal / 2048))
    shmall=$((memTotal / 4))
    if [ $shmall -lt 2097152 ]; then
        shmall=2097152
    fi
    shmmax=$((memTotal * 1024 - 1))
    if [ "$shmmax" -lt 4294967295 ]; then
        shmmax=4294967295
    fi
    
    sed -i '/^\s*kernel.shmall/'d /etc/sysctl.conf
    echo "kernel.shmall = $shmall" >> /etc/sysctl.conf
    
    sed -i '/^\s*kernel.shmmax/'d /etc/sysctl.conf
    echo "kernel.shmmax = $shmmax" >> /etc/sysctl.conf
    
    sysctl -p
}

configNTP() {
    sed -i '/^\s*OPTIONS/'d /etc/sysconfig/ntpd
    sed -i '/^\s*SYNC_HWCLOCK/'d /etc/sysconfig/ntpd
    
    echo 'OPTIONS="-x -u ntp:ntp -p /var/run/ntpd.pid -g"' >>/etc/sysconfig/ntpd
    echo 'SYNC_HWCLOCK=yes' >>/etc/sysconfig/ntpd

    if [ "$INIT_TYPE" = 'systemd' ];then
        systemctl restart ntpd
    else
        service ntpd restart
    fi
}

configI18nLANG() {
    sed -i '/^LANG/'d /etc/sysconfig/i18n
    echo 'LANG=en_US.UTF-8' >>/etc/sysconfig/i18n
}

configSshd() {
    sed -i '/^\s*LoginGraceTime/'d /etc/ssh/sshd_config
    echo 'LoginGraceTime 0' >>/etc/ssh/sshd_config
}

configNetworking() {
    sed -i '/^\s*NETWORKING/'d /etc/sysconfig/network
    sed -i '/^\s*NOZEROCONF/'d /etc/sysconfig/network
    echo 'NETWORKING=yes' >>/etc/sysconfig/network
    echo 'NOZEROCONF=yes' >>/etc/sysconfig/network
}

disableTransHugepage() {
    sed -i '/GRUB_CMDLINE_LINUX/'s'/quiet/quiet transparent_hugepage=never numa=off/' /etc/default/grub
    
    if [ -f /sys/kernel/mm/redhat_transparent_hugepage/enabled ]; then
        echo never > /sys/kernel/mm/redhat_transparent_hugepage/enabled
    fi
    if [ -f /sys/kernel/mm/redhat_transparent_hugepage/defrag ]; then
        echo never > /sys/kernel/mm/redhat_transparent_hugepage/defrag
    fi
}

configShmDev() {
    sed -i '/^\s*\/dev\/shm\s/'s'/defaults/rw,exec/' /etc/fstab
    mount -o remount /dev/shm
}

enableNscd() {
    chkconfig --level 35 nscd on
    if [ "$INIT_TYPE" = 'systemd' ];then
        systemctl restart nscd
    else
        service nscd restart
    fi
}

disableSELinux() {
    sed -i '/^SELINUX/'d /etc/selinux/config
    echo "SELINUX=disabled" >>/etc/selinux/config
    setenforce 0
}


main() {
    ps -p1 | grep systemd >/dev/null && INIT_TYPE="systemd" || INIT_TYPE="sysvinit"
    
    echo "--Turning NetworkManager off-------------"
    disableNetworkManager
    
    echo "--Stop iptables--------------------------"
    disableIptables
    
    echo "--Disable selinux------------------------"
    disableSELinux
    
    echo "--Config yum local repo------------------"
    configYumLocalRepo
    
    echo "--Depenndency package install------------"
    dependRpmInstall
    
    echo "--Config Lang----------------------------"
    configI18nLANG
    
    echo "--Config sshd----------------------------"
    configSshd
    
    echo "--Config ntp-----------------------------"
    configNTP
    
    echo "--Config networking----------------------"
    configNetworking
    
    echo "--disableTransHugepage-------------------"
    disableTransHugepage
    
    echo "--config fstab---------------------------"
    configShmDev
    
    echo "--Config nscd----------------------------"
    enableNscd
    
    echo "--Tunning shm config in sysctl.conf------"
    tuningShmConf
}

storage=$3

main
