#!/bin/bash
function DO_CMD() {
    echo Exec ommand: $@
    $@

    if [ $? != 0 ]; then
        HAS_ERROR=$?
        echo ERROR: Execute failed.
        exit $HAS_ERROR
    else
        echo FIND: Execute success.
    fi
}

INVENTORY_DIR=$1

DO_CMD $ENVENTORY_DIR/orainstRoot.sh
DO_CMD $ORACLE_HOME/root.sh

exit $HAS_ERROR
