#!/bin/bash
function DO_CMD() {
    echo Exec ommand: $@
    $@

    if [ $? != 0 ]; then
        HAS_ERROR=$?
        echo ERROR: Execute failed.
        exit $HAS_ERROR
    else
        echo FIND: Execute success.
    fi
}

INVENTORY_DIR=$(cat $ORACLE_HOME/oraInst.loc | grep inventory_loc | sed s'/inventory_loc\s*=\s*//' | sed s'/\s*$//')

DO_CMD $INVENTORY_DIR/orainstRoot.sh
DO_CMD $ORACLE_HOME/root.sh

exit $HAS_ERROR
