#!/bin/bash

configOracleUlimit() {
    grep 'ulimit -n 65536' /etc/profile >/dev/null
    if [ $? = 0 ];then
        return
    fi
    
    cat >>/etc/profile <<EOF
if [ \$USER = "oracle" ] || [ \$USER = "grid" ]; then
    if [ \$SHELL = "/bin/ksh" ]; then
        ulimit -p 16384
        ulimit -n 65536
    else
        ulimit -u 16384 -n 65536
    fi
        umask 022
fi
EOF
}

createOraDir() {
    mkdir -p /oracle/app/oracle
    mkdir -p /oracle/app/oracle/cfgtoollogs
    mkdir -p /oracle/app/oracle/product/12.1.0/db_1
    chown -R oracle:oinstall /oracle/app/oracle
    chmod -R 775 /oracle/app/oracle
    
    mkdir -p /oracle/app/oraInventory
    chown -R grid:oinstall /oracle/app/oraInventory
    chmod -R 775 /oracle/app/oraInventory
    
    mkdir -p /oracle/app/grid
    mkdir -p /oracle/app/12.1.0/grid
    chown -R grid:oinstall /oracle/app/grid
    chown -R grid:oinstall /oracle/app/12.1.0/grid
    chmod -R 775 /oracle/app/grid
    chmod -R 775 /oracle/app/12.1.0/grid
}

unzipMedia(){

}

installCvuqdisk() {
    #single node:rpm -ivh /software/grid/rpm/cvuqdisk-1.0.9-1.rpm
    export CVUQDISK_GRP=oinstall
    rpm -ivh /software/grid/rpm/cvuqdisk-1.0.9-1.rpm
    
    #rac:
    export CVUQDISK_GRP=oinstall
    rpm -ivh /software/cvuqdisk-1.0.9-1.rpm
}
