#!/usr/bin/perl
use FindBin;
use lib "$FindBin::Bin/lib";
use lib "$FindBin::Bin/lib/perl-lib/lib/perl5";

use strict;
use IO::File;
use Getopt::Long;
use JSON;

use PostgresqlExec;
use AutoExecUtils;

sub usage {
    my $pname = $FindBin::Script;

    print("$pname --OS_USER <OS_USER> --DB_NAME <DB_NAME>\n");
    exit(1);
}

sub main {
    my $opts = {};
    GetOptions(
        $opts, qw{
            OS_USER=s
            HOST=s
            SOCK_DIR=s
            PORT=s
            DB_NAME=s
            SQL=s
            verbose=i
        }
    );

    my $hasOptErr = 0;

    my $node = $opts->{node};
    my $nodeObj;
    if ( defined($node) and $node ne '' ) {
        $nodeObj = from_json($node);
    }
    else {
        my $nodeJson = $ENV{AUTOEXEC_NODE};
        if ( defined($nodeJson) and $nodeJson ne '' ) {
            $nodeObj = from_json($nodeJson);
        }
    }
    if ( not defined($nodeObj) ) {
        print("ERROR: Must defined remote node by option --node or environment AUTOEXEC_NODE\n");
        $hasOptErr = 1;
    }

    my $OS_USER  = $opts->{OS_USER};
    my $HOST     = $opts->{HOST};
    my $SOCK_DIR = $opts->{SOCK_DIR};
    my $PORT     = $opts->{PORT};
    my $DB_NAME  = $opts->{DB_NAME};
    my $sqlTxt   = $opts->{SQL};
    my $verbose  = $opts->{verbose};

    if ( not defined($OS_USER) or $OS_USER eq '' ) {
        $hasOptErr = 1;
        print("ERROR: Must defined OS_USER by option --OS_USER.\n");
    }
    if ( $hasOptErr == 1 ) {
        usage();
    }

    my $host = $HOST;
    if ( defined($SOCK_DIR) and $SOCK_DIR ne '' and -e $SOCK_DIR ) {
        $host = $SOCK_DIR;
    }

    $sqlTxt =~ s/^\s*|\s*$//sg;
    $sqlTxt =~ s/\\n/\n/sg;
    $sqlTxt = $sqlTxt . "\n";

    my $psql = PostgresqlExec->new( osUser => $OS_USER, host => $host, port => $PORT, dbname => $DB_NAME );

    my $exitCode = $psql->do(
        sql     => $sqlTxt,
        verbose => $verbose
    );

    my $hasError = 0;
    if ( $exitCode != 0 ) {
        $hasError = 1;
        print("ERROR: Errors occur while executing sql.\n");
    }
    else {
        print("FINE: Execute sql scripts success.\n");
    }

    return $hasError;
}

exit( main() );
