#!/bin/bash
#卸载某个节点上的Oracle Database软件

HAS_ERROR=0
function DO_CMD() {
    echo Exec command: $@
    $@
    EXIT_CODE=$?
    if [ $EXIT_CODE != 0 ]; then
        HAS_ERROR=1
        echo ERROR: Execute $@ failed.
        exit $EXIT_CODE
    else
        echo FINE: Execute success.
    fi
}

function SUDO_ORA_CMD() {
    USER=$1
    shift
    echo "Exec command: su - '$USER' -c '$@'"
    eval "su - '$USER' -c '$@'"
    exitCode=$?
    if [ $exitCode -ge 128 ]; then
        #负数返回码，大于127就是负数的补码
        echo "ERROR: Execute command failed, exitCode:$exitCode."
        exit $exitCode
    elif [ $exitCode -gt 0 ]; then
        echo "WARN: Execute command  has some warning, exitCode:$exitCode."
    else
        echo "FINE: All operations were successful."
    fi
}

function SUDO_CMD_CONT() {
    USER=$1
    shift
    echo "Exec command: su - '$USER' -c '$@'"
    eval "su - '$USER' -c 'AUTOEXEC_JOBID=$AUTOEXEC_JOBID $@'"
    EXIT_CODE=$?
    if [ $EXIT_CODE != 0 ]; then
        HAS_WARN=1
        echo WARN: Execute $@ failed.
    else
        echo FINE: Execute success.
    fi
}

function removeUserAndGroups() {
    if [ -z "$ORACLE_UID" ]; then
        return
    fi

    usermod -g10 $ORACLE_USER

    #delete group id bigger than 1000
    groups=$(id -G $ORACLE_USER)
    for oraGid in $(id -G $ORACLE_USER); do
        if [ $oraGid -gt 1000 ]; then
            groupName=$(getent group GID | cut -d: -f1)
            groupdel $groupName
        fi
    done

    #delete oracle_user
    userdel $ORACLE_USER
}

#参数处理,全部用长参数
######################################
function parseOpts() {
    OPT_SPEC=":h-:"
    while getopts "$OPT_SPEC" optchar; do
        case "${optchar}" in
        -)
            case "${OPTARG}" in
            CV_ASSUME_DISTID)
                CV_ASSUME_DISTID="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            ORACLE_USER)
                ORACLE_USER="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            LEFT_NODES)
                LEFT_NODES="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            DEL_USER)
                DEL_USER="${!OPTIND}"
                OPTIND=$(($OPTIND + 1))
                ;;
            *)
                if [ "$OPTERR" = 1 ] && [ "${OPT_SPEC:0:1}" != ":" ]; then
                    echo "Unknown option --${OPTARG}" >&2
                fi
                ;;
            esac
            ;;
        h)
            usage
            exit 2
            ;;
        *)
            if [ "$OPTERR" != 1 ] || [ "${OPT_SPEC:0:1}" = ":" ]; then
                echo "Non-option argument: '-${OPTARG}'" >&2
            fi
            ;;
        esac
    done
}

parseOpts "$@"

if [ -z "$ORACLE_USER" ]; then
    ORACLE_USER=oracle
fi

ORACLE_UID=$(id -u $ORACLE_USER 2>/dev/null)
if [ -z "$ORACLE_UID" ]; then
    echo "WARN: User $ORACLE_USER not exists, maybe already uninstalled."
fi

ENV_DISTID=""
if [ "$CV_ASSUME_DISTID" != "AUTO" ]; then
    ENV_DISTID="CV_ASSUME_DISTID=$CV_ASSUME_DISTID"
fi

oraEnv=$(SUDO_ORA_CMD $ORACLE_USER env | grep ORACLE_)
echo "$oraEnv"
eval "$oraEnv"

#========开始执行删除操作==============================

if [ ! -f "$ORACLE_HOME/bin/dbca" ]; then
    echo "WARN: Deinstall script $ORACLE_HOME/bin/dbca not exists, maybe already uninstalled."
    exit 0
fi

echo "Try to update inventory on node $LEFT_NODES..."
SUDO_ORA_CMD $ORACLE_USER $ORACLE_HOME/oui/bin/runInstaller -silent -force -noconfig -ignorePrereq -ignoreSysPrereqs \
    -local -updateNodeList \
    "ORACLE_HOME=$ORACLE_HOME" \
    "CLUSTER_NODES={$LEFT_NODES}"

if [ ! -f "$ORACLE_HOME/deinstall/deinstall" ]; then
    echo "WARN: Deinstall script $ORACLE_HOME/deinstall/deinstall not exists, maybe already uninstalled."
    exit 0
fi

echo "Try to deinstall oracle database software on node $LEFT_NODES..."
SUDO_ORA_CMD $ORACLE_USER $ORACLE_HOME/deinstall/deinstall -local

if [ -n "$ORACLE_BASE" ] && [ -e "$ORACLE_BASE/admin" ]; then
    rm -rf "$ORACLE_BASE/admin"
fi

if [ "$DEL_USER" == "1" ]; then
    removeUserAndGroups
fi

echo "Try to clean the .ssh rsa auhroized config..."
SUDO_CMD_CONT $ORACLE_USER rm -rf "~/.ssh/*"

exit $HAS_ERROR
